### ISSUE TITLE
Availability Status

### ISSUE THREAD

**Issue by amitsamanta996** [milothomas/ha-miraie-ac#2]
Availability status not working properly, but working perfectly in miraie app.
I didn't see any available status in their mqtt, probably they use some api

**Comment by milothomas** [comment]
> Availability status not working properly, but working perfectly in miraie app. I didn't see any available status in their mqtt, probably they use some api

Does the entity show as "Unavailable"? I started seeing this lately after a HomeAssistant/Node-Red restart. Could you try moving the MirAIe node and deploy the Node-Red flow flow and see if that causes it to update? (changing the position of the node should enable the "Deploy" button on the flow)

**Comment by amitsamanta996** [comment]
It shows available all the time, doesn't matter if device is unavailable or not

**Comment by amitsamanta996** [comment]
in your code
`state.onlineStatus === "false" ? "offline" : "online"`
but their mqtt payload doesn't have onlineStatus value

mqtt payload of /status
`{
  "ty": "AC",
  "acpm": "off",
  "acfs": "low",
  "acvs": 5,
  "achs": 0,
  "acng": "off",
  "acdc": "on",
  "acec": "off",
  "acem": "off",
  "actm": [
    -1,
    -1
  ],
  "acfc": "off",
  "acdl": 0,
  "acms": "off",
  "acgm": 0,
  "acmss": 0,
  "acpms": 0,
  "V": "1.65",
  "acsp": "none",
  "rmtmp": "22.5",
  "actmp": "27.0",
  "acmd": "cool",
  "ts": "1643275367",
  "ps": "off",
  "sid": "2581",
  "cnt": "ava",
  "lcmd": "ps",
  "rssi": -58
}`

**Comment by milothomas** [comment]
> but their mqtt payload doesn't have onlineStatus value

True, but the fact that you are getting a response for /status means that the device is online, no?

So `state.onlineStatus === "false" ? "offline" : "online"` should return "online" for HA to show the device as a available.

**Comment by amitsamanta996** [comment]
yes, the thing is it's always online. 
When I turn off power to my AC, miraie app shows offline, but homeassistant shows online.
I want home assistant to show unavailable when power to AC is cut off

**Comment by amitsamanta996** [comment]
> ,

/status has retain enabled so its gives the last value, it doesn't check if device power is cut off.

Miraie app shows offline in such case, I don't know how exactly their app is updating that status

**Comment by milothomas** [comment]
Gotcha, I didn't see the retained flag. I wonder if there is a LWT message; have you seen one?

**Comment by amitsamanta996** [comment]
mqtt has option for availability so when a device goes offline, mqtt server automatically updates the status, but its not sending anything on /status
my guess is they are using http api to check device is offline or not

**Comment by milothomas** [comment]
Yea but I was trying to avoid polling the API and open up a can of worms. I guess this is the last resort. I'll check for an LWT message for the time being.

**Comment by amitsamanta996** [comment]
also, can you add support for swings and powerful mode?
"acvs" : 0 
can be any value from 0 to 5, where 0 is auto and 1 to 5 are different positions
"acpm" : "off"  or  "on"
acpm can only be on if ac is in cool mode, so you can add "powerful" in list of modes, and some code when powerful mode selected set acmd to cool  and acpm to on, otherwise set acpm to off

**Comment by milothomas** [comment]
> > I'll check for an LWT message for the time being.
> 
> I am sure AC has a LWT message, all mqtt devices does, I just don't have a way to intercept the mqtt messages between AC and their server and MQTT Explorer doesn't show anything unless its subscribed

The messages on `/connectionStatus` looks promising, but I don't see what/when triggers this message. The first time it came almost instantly, subsequent attempts took their own sweet time.
`
{
  "deviceId" : "...",
  "connectedTime" : 1643294556155,
  "updatedTime" : 1643295096173,
  "nextUpdate" : 1643295096173,
  "onlineStatus" : "false"
}
`

**Comment by amitsamanta996** [comment]
Yes, I will also check and let you know, LWT messages takes some time to trigger after connection is lost

**Comment by amitsamanta996** [comment]
/connectionStatus working perfectly, its updating with miraie app same time.
just need the onlineStatus from here

Please make a update add this topic and 2 features said above.

**Comment by amitsamanta996** [comment]
/connectionStatus has retain enabled, it triggers true when ac connects to their server and triggers false after few seconds of ac disconnected

**Comment by milothomas** [comment]
New version (1.0.3) has been published, it should sort out the availability issues.
