### ISSUE TITLE
Login with email? Gives Error 412 with mobile

### ISSUE THREAD

**Issue by pravardhanreddy** [milothomas/ha-miraie-ac#9]
While signing up for MirAI, I used my email and had entered a phone number which was later deactivated and I was not able to verify my phone number. When I try to enter the credentials on Node-RED I get the following error
```
"Error: Request failed with status code 412"
```
MirAI app doesn't let me enter another phone number.
Is it possible to perform the login using the email id?

**Comment by milothomas** [comment]
@pravardhanreddy, please update to v1.2.0 to select the auth type (email).

Let me know how it goes.
